### PR TITLE
Gg/timeseries

### PR DESCRIPTION
**Pull request by gordonguthrie**
Major pull request - rejigging lexer/parser to get integration with the query engine. Top changes include:
* switching the old intermediate output of the parser to a riak_sql record for readability
* reorganising how data colocation is expressed in the create table functionality

### CODE REVIEW

**Comment by bkerley** [comment]
This looks reasonable, but I'm concerned about the structure naming changes and how they'll break other code.

**Comment by andytill** [comment]
+1 04ca993f30532b66ef277daffb7943b9cc79363c

**Comment by gordonguthrie** [comment]
bishop merge

**Comment by jonmeredith** [comment]
@borshop merge

silly play on words... bishop internal bot, bors Pr management system, so obviously you have to talk to mention borshop

**Pull request merged**
