### PR TITLE
fix up tabs and white space problems

### PR DESCRIPTION
**Pull request by gordonguthrie**

### CODE REVIEW

**Comment by andytill** [comment]
+1 8eec466

**Comment by gordonguthrie** [comment]
merge borshop

[I am leaving this comment here as a monument to my idiocy]

**Comment by gordonguthrie** [comment]
@borshop merge

**Comment by hmmr** [comment]
+1 8eec466

**Comment by hmmr** [comment]
@borshop merge

**Comment by andytill** [comment]
@borshop merge

**Pull request merged**
