### PR TITLE
SQL IN keyword RTS-1733

### PR DESCRIPTION
**Pull request by andytill**
Support the SQL `IN` keyword.

```sql
SELECT * FROM mytable
WHERE myval IN ('a', 'b', 'c', 'd');
```

RFC: https://github.com/basho/rfc/pull/60

### CODE REVIEW

**Comment by paegun** [comment]
The test comparing the result of `<field> IN (<values>)` and the expanded `(<field> = <value1> OR ... <field> = <valueN>)` is great.

The reuse of RowValueList also seems to reduce testing of invalid SQL, i.e. `... WHERE a IN` (missing values), and helpfulness of the error message for that case does remain good, "syntax error before: IN". This error message could be better, but is IMHO good UX while not over-investing in error reporting.

However, a test of empty values for IN fails w/ "no function clause matching ...". Please add a test for empty values and create a function head for empty values.

**Comment by andytill** [comment]
Top notch input testing. In postgres 9.3, an empty `IN` predicate causes a syntax error.

```sql
SELECT * FROM COMPANY WHERE name IN ();
-- ERROR: syntax error at or near ")"
```

I'll make TS return an error in this case.

**Comment by hazen** [comment]
:+1:

**Comment by macintux** [comment]
+1

**Pull request merged**
