### PR TITLE
Use a macro for the param record name

### PR DESCRIPTION
**Pull request by andytill**
Like `?DDL`, so that version changes in the record name do not affect the rest of the code.

This is in advance of the DDL upgrade and down work, to ease changes in so I don't have to merge whenever a function head is modified.

### CODE REVIEW

**Comment by hmmr** [comment]
Vote for a more descriptive macro name (and incidentally, the name of the record itself). _If_ Erlang had namespaces, identifiers like "param" would be just as fine, but you never know what rogue .hrl might invent their own ?PARAM.

**Comment by andytill** [comment]
You are proposing a very large scope increase for this change, which can otherwise go into 1.4.  Maybe raise a JIRA for that?

**Comment by hmmr** [comment]
`RIAK_SQL_DDL_PARAM` can be it, and similarly, `#riak_sql_ddl_param_v1{}`. Perhaps leave `#param_v1` alone, now that it appears the rename would affect huge amount of files.

**Comment by andytill** [comment]
Looks like we have a compromise on `?SQL_PARAM`.

**Comment by hmmr** [comment]
+1 9fa5ca0368

**Comment by andytill** [comment]
@borshop merge

**Pull request merged**
