### PR TITLE
RTS-252 binary field names

### PR DESCRIPTION
**Pull request by andytill**
This PR changes strings used for field names and token chars to binaries across all types and functions.  This has been done at the lexer level so anything coming into the parser should already be of the correct type and not need to be converted to a binary.

The reason for this PR differentiate easily between lists used as part of the data structure such as paths (lists of field names) and lists of paths.

### CODE REVIEW

**Comment by hmmr** [comment]
+1

**Comment by hmmr** [comment]
@borshop merge

**Comment by gordonguthrie** [comment]
@borshop merge

**Comment by gordonguthrie** [comment]
+1 655c11a

**Comment by gordonguthrie** [comment]
+1 b55c11a

**Comment by gordonguthrie** [comment]
+1 9c7abf9

**Pull request merged**
