### PR TITLE
Descending Keys

### PR DESCRIPTION
**Pull request by andytill**
Relies on https://github.com/basho/riak_kv/pull/1401. See this PR for an explanation as to how descending keys works.

Tests in basho/riak_test#1055
##### `field_orders/0`

Returns the orders of the local key elements.

``` erlang
field_orders() -> [ascending, ascending, descending].
```

For table definition.

``` sql
CREATE TABLE table1 (
a SINT64 NOT NULL,
b SINT64 NOT NULL,
c TIMESTAMP NOT NULL,
PRIMARY KEY ((a,b,quantum(c, 1, 's')), a,b,c DESC));
```
##### `revert_ordering_on_local_key/1`

Given a local key that has been through the descending keys transform, revert it to it's original value.
#### Change to `param_v1` record

An `ordering` field has been added which will be set for the local key params. This will need some upgrade/downgrade work.
#### `riak_ql_ddl`

Descending keys transform functions.
#### `riak_ql_lexer`, `riak_ql_parser`

Support for the `DESC` keyword. Validations for correct usage.

### CODE REVIEW

**Comment by erikleitch** [comment]
**riak_ql_quanta.erl**
- Contains tabs, probably not introduced in this PR, but should take the opportunity to get rid of them
- Swapping start and end keys for range scans should work, given our present restrictions on PK construction.  However if that evolves,we should not forget that we've done this.  Perhaps put a comment in riak_kv_eleveldb_backend:range_scan where these keys are used to make explicit what is happening in the case of descending-order keys?

**rebar.config**
- Contains reference to unite repo, which is not under basho control.  Explicit tag references (i.e., v0.0.1) would cause compile to fail on this branch if they disappeared.  Are we intending to use this repo more extensively going forward?

**src/riak_ql_ddl.erl**
- To what does this comment refer, and what should we do about it?
  
  ```
  %% TODO there is a mismatch between how the fields in the where   clause                                                                      
  %% and the fields in the DDL are mapped 
  ```

**src/riak_ql_ddl_compiler.erl**
- Why is this done twice, or is this just a typo?
  
  ```
    {RevertOrderingFn, LineNo11} = build_revert_ordering_on_local_key_fn(DDL, LineNo10),
    {FieldOrdersFn, LineNo10} = build_field_orders_fn(DDL, LineNo9),
    {RevertOrderingFn, LineNo11} = build_revert_ordering_on_local_key_fn(DDL, LineNo10),
  ```

**src/riak_ql_keywords.csv, riak_ql_lexer.xrl, and riak_ql_parser.yrl**
- What is the logic behind supporting the ASC keyword, if this is our default and can only be changed by supplying the DESC keyword?

**Comment by erikleitch** [comment]
And note that this branch does not work with the new primary-key schema that allows additional fields in the local key over the partition-key fields.  Probably this was branched before that functionality was added?

**Comment by andytill** [comment]
@erikleitch in what way doesn't it work, can you suggest a failing test?

@andytill The failure I'm seeing is when I use the listkeys fix I sent you with a DDL that includes extra fields in the local key, like:

```
get_ddl(api_desc) ->
    _SQL = "CREATE TABLE GeoCheckin (" ++
        "myfamily    varchar     not null, " ++
        "myseries    varchar     not null, " ++
        "time        timestamp   not null, " ++
        "myint       sint64      not null, " ++
        "mybin       varchar     not null, " ++
        "myfloat     double      not null, " ++
        "mybool      boolean     not null, " ++
        "PRIMARY KEY ((myfamily, myseries, quantum(time, 15, 'm')), " ++
        "myfamily, myseries, time, mybin))";
```

now when riak_ql_ddl:get_local_key() is called in the key conversion function during the listkeys, Mod:extract/2 throws an error like:

```
10:47:41.937 [error] gen_server <0.918.0> terminated with reason: bad argument in 'riak_ql_table_GeoCheckin$1':extract/2 line 4
```

**NB** This does _not_ happen when I replace field mybin with myint in the example above, so this seems to have something to do with varchar types.

this occurs in get_local_key --> build --> Mod:extract(Obj, Nm) when attempting to extract field 'mybin' from the object {<<"family1">>,<<"seriesX">>,900000, <<"test1">>}.  (Seems like this should return <<"test1">>, unless there's a mismatch in the DDL, but the key-related parts of the DDL look correct, (suggesting that something's going wrong when the module itself is constructed?)): 

```
 {key_v1,
                                                                              [{param_v1,
                                                                                [<<"myfamily">>],
                                                                                undefined},
                                                                               {param_v1,
                                                                                [<<"myseries">>],
                                                                                undefined},
                                                                               {hash_fn_v1,
                                                                                riak_ql_quanta,
                                                                                quantum,
                                                                                [{param_v1,
                                                                                  [<<"time">>],
                                                                                  undefined},
                                                                                 15,
                                                                                 m],
                                                                                timestamp}]},
                                                                             {key_v1,
                                                                              [{param_v1,
                                                                                [<<"myfamily">>],
                                                                                undefined},
                                                                               {param_v1,
                                                                                [<<"myseries">>],
                                                                                undefined},
                                                                               {param_v1,
                                                                                [<<"time">>],
                                                                                undefined},
                                                                               {param_v1,
                                                                                [<<"mybin">>],
                                                                                undefined}]}}
```

**Comment by andytill** [comment]
> To what does this comment refer, and what should we do about it?
> 
> %% TODO there is a mismatch between how the fields in the where clause
> %% and the fields in the DDL are mapped 

This is dated back to August 2015 and I'm not sure what it refers to. Possibly that where clauses are hierarchical but table fields are not, or the names are just a binary in the where, not a binary in a list.

> What is the logic behind supporting the ASC keyword, if this is our default and can only be changed by supplying the DESC keyword?

It wasn't added because it is the default value so doesn't modify the key, I can add it if you like?

@andytill  I meant the opposite, actually.  There's added code in riak_ql_keywords.csv and riak_ql_lexer.xrl to support the ASC keyword, and I'm wondering why it was added when we _don't_ need to support an explicit ASC keyword...

> Why is this done twice, or is this just a typo?
> 
> {RevertOrderingFn, LineNo11} = build_revert_ordering_on_local_key_fn(DDL, LineNo10),
> {FieldOrdersFn, LineNo10} = build_field_orders_fn(DDL, LineNo9),
> {RevertOrderingFn, LineNo11} = build_revert_ordering_on_local_key_fn(DDL, LineNo10),

I think it was a merge fart, removed the duplication in 7abb6ec.

> Swapping start and end keys for range scans should work, given our present restrictions on PK construction. However if that evolves,we should not forget that we've done this. Perhaps put a comment in riak_kv_eleveldb_backend:range_scan where these keys are used to make explicit what is happening in the case of descending-order keys?

Commented in `riak_kv_elelveldb` that the start/end keys could be switched for descending keys in https://github.com/basho/riak_kv/pull/1401/commits/29f415846fc0623df4b71aad8bf3b2dba4e00452.

**Comment by erikleitch** [comment]
@andytill I've figured out what the problem is, and the fix requires either some extra work in the ddl compiler, or a function in riak_ql_ddl that simply processes each field in the primary key in order without using the riak_ql_table_TableName$1 built-ins.  It also means that listkeys is still in general broken, though it works under certain restricted circumstances.

The issue with listkeys is that when the key conversion function is called during the eleveldb fold, only  the key is available to the conv fn, a la:

```
KeyConvFn =
        fun(Key) when is_binary(Key) ->
                PossiblyNegatedRow = sext:decode(Key),
                LocalKey = riak_ql_ddl:get_local_key(DDL, PossiblyNegatedRow, Mod),
                UnnegatedRow = riak_kv_ts_util:encode_typeval_key(LocalKey),
                riak_kv_ts_util:row_to_key(UnnegatedRow, DDL, Mod);
```

The _key_ is sext:decoded, and the resulting object is passed to riak_ql_ddl:get_local_key to construct a formatted local key.  But because that object was decoded from the key, it only contains the local key fields, not the complete set of fields in the table schema for this table.  And riak_ql_ddl:get_local_key needs the full set of fields to be present in the tuple, because it passes the tuple to riak_ql_ddl:build, which iterates over each field in the local key, calling Mod:extract on it to extract it from a complete row.  

Mod:extract is the hardwired function built at table compile-time by riak_ql_ddl_compiler:compile, which only knows the index of each field in a complete tuple, and attempts to extract it by that index.  

So if your local key happens to be constructed from the first M fields of an N-field table schema, there's no problem, and listkeys works fine.

But what happens if your local key is constructed of fields that don't happen to be the first M fields in your N-field table schema?  You decode the key, which gives you an object that only contains those M fields, then you pass that object to Mod:extract, which tries to extract each field by its N-relative index, and kaboom!  

Consider my example:

```
get_ddl(api_desc) ->
    _SQL = "CREATE TABLE GeoCheckin (" ++
        "myfamily    varchar     not null, " ++
        "myseries    varchar     not null, " ++
        "time        timestamp   not null, " ++
        "myint       sint64      not null, " ++
        "mybin       varchar     not null, " ++
        "myfloat     double      not null, " ++
        "mybool      boolean     not null, " ++
        "PRIMARY KEY ((myfamily, myseries, quantum(time, 15, 'm')), " ++
        "myfamily, myseries, time, mybin))";
```

the Mod:extract function now looks like this:

```
extract(Obj, [<<"myfamily">>]) when is_tuple(Obj) ->
    element(1, Obj);
extract(Obj, [<<"myseries">>]) when is_tuple(Obj) ->
    element(2, Obj);
extract(Obj, [<<"time">>]) when is_tuple(Obj) ->
    element(3, Obj);
extract(Obj, [<<"myint">>]) when is_tuple(Obj) ->
    element(4, Obj);
extract(Obj, [<<"mybin">>]) when is_tuple(Obj) ->
    element(5, Obj);
extract(Obj, [<<"myfloat">>]) when is_tuple(Obj) ->
    element(6, Obj);
extract(Obj, [<<"mybool">>]) when is_tuple(Obj) ->
    element(7, Obj).
```

Now when I decode the key, I get an object like:

```
Obj = {<<"family1">>,<<"seriesX">>,900000, <<"test1">>}
```

when it gets passed to Mod:extract(Obj, [<<"mybin">>]), Mod:extract/2 tries to extract field <<"mybin">> from element 5 of the object, but it isn't element 5, it's element 4, and furthermore there is no element 5, so the process bombs out with an error.

**Comment by hmmr** [comment]
There will probably be a need to revisit `riak_ql_ddl:get_partition_key/3` and make certain the quantum field gets reset to the right quantum boundary depending on whether that field is DESC or ASC qualified. The relevant riak_test module is ts_cluster_list_irreg_keys_SUITE (see https://github.com/basho/riak_test/pull/1081 and https://github.com/basho/riak_kv/pull/1427 for the context).

**Pull request merged**
