### PR TITLE
Fail early on multiple table selects

### PR DESCRIPTION
**Pull request by macintux**
Extended @javajolt's changes to supply same error message as KV gives us today when multiple tables are submitted.

Supersedes #130.

### CODE REVIEW

**Comment by javajolt** [comment]
:+1:85d0b5b

**Comment by javajolt** [comment]
:+1:0e9843e

**Comment by hazen** [comment]
+1 0e9843e

**Comment by hazen** [comment]
@borshop is on holiday. YOLO merging.

**Pull request merged**
